import { NextRequest, NextResponse } from 'next/server';
import { adminReportFlow } from '@/ai/flows/admin-reports';
import { sendAdminReportEmail } from '@/lib/admin-email';

/**
 * @fileOverview Cron endpoint to trigger the weekly executive summary.
 * GET /api/cron/weekly-summary?secret=<CRON_SECRET>
 */

export const dynamic = 'force-dynamic';
export const maxDuration = 300; 

export async function GET(request: NextRequest) {
  // 1. Auth gate
  const cronSecret = process.env.CRON_SECRET;
  if (!cronSecret) {
    return NextResponse.json(
      { error: 'CRON_SECRET not configured.' },
      { status: 403 }
    );
  }

  const providedSecret = request.nextUrl.searchParams.get('secret');
  if (providedSecret !== cronSecret) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
  }

  try {
    // 2. Run Genkit Flow to generate report
    const { summary, metrics } = await adminReportFlow();

    // 3. Construct HTML email
    const emailHtml = `
      <div style="font-family: sans-serif; color: #333; max-width: 600px; margin: auto;">
        <h1 style="color: #1a73e8;">The CFO: Weekly Performance Audit</h1>
        <p style="font-size: 0.9em; color: #666;">Period: ${metrics.dateRange.start} to ${metrics.dateRange.end}</p>
        
        <hr style="border: 0; border-top: 1px solid #eee; margin: 20px 0;" />
        
        <div style="background: #f8f9fa; padding: 20px; border-radius: 8px; margin-bottom: 20px;">
          <p style="white-space: pre-wrap; line-height: 1.6;">${summary}</p>
        </div>

        <h3 style="margin-bottom: 10px;">Operational Metrics</h3>
        <table style="width: 100%; border-collapse: collapse;">
          <tr style="background: #f1f3f4;">
            <td style="padding: 8px; border: 1px solid #ddd;">Total User Base</td>
            <td style="padding: 8px; border: 1px solid #ddd; font-weight: bold;">${metrics.totalUsers}</td>
          </tr>
          <tr>
            <td style="padding: 8px; border: 1px solid #ddd;">Daily Active Users (DAU)</td>
            <td style="padding: 8px; border: 1px solid #ddd; font-weight: bold;">${metrics.dau}</td>
          </tr>
          <tr style="background: #f1f3f4;">
            <td style="padding: 8px; border: 1px solid #ddd;">Weekly Active Users (WAU)</td>
            <td style="padding: 8px; border: 1px solid #ddd; font-weight: bold;">${metrics.wau}</td>
          </tr>
          <tr>
            <td style="padding: 8px; border: 1px solid #ddd;">New Acquisitions (Week)</td>
            <td style="padding: 8px; border: 1px solid #ddd; font-weight: bold;">${metrics.newUsersWeek}</td>
          </tr>
        </table>

        <h3 style="margin-top: 20px; margin-bottom: 10px;">Activity Throughput</h3>
        <table style="width: 100%; border-collapse: collapse;">
          <tr style="background: #f1f3f4;">
            <td style="padding: 8px; border: 1px solid #ddd;">Food Logs Recorded</td>
            <td style="padding: 8px; border: 1px solid #ddd; font-weight: bold;">${metrics.totalFoodLogsWeek}</td>
          </tr>
          <tr>
            <td style="padding: 8px; border: 1px solid #ddd;">Exercise Logs Recorded</td>
            <td style="padding: 8px; border: 1px solid #ddd; font-weight: bold;">${metrics.totalExerciseLogsWeek}</td>
          </tr>
          <tr style="background: #f1f3f4;">
            <td style="padding: 8px; border: 1px solid #ddd;">AI/LLM Operations</td>
            <td style="padding: 8px; border: 1px solid #ddd; font-weight: bold;">${metrics.totalLLMCallsWeek}</td>
          </tr>
        </table>

        <p style="font-size: 0.8em; color: #999; margin-top: 30px;">
          This report was automatically generated by the CFO Genkit Admin Flow.
        </p>
      </div>
    `;

    // 4. Send Email
    const result = await sendAdminReportEmail(
      'nicholas.switzer@gmail.com',
      `[The CFO] Weekly Summary: ${metrics.dau} DAU / ${metrics.wau} WAU`,
      emailHtml
    );

    return NextResponse.json({
      ok: true,
      metrics,
      emailSent: result.success,
    });
  } catch (error) {
    console.error('Weekly summary error:', error);
    return NextResponse.json(
      { error: 'Internal server error', details: String(error) },
      { status: 500 }
    );
  }
}
